In [2]:
# Q1.  Array operations and vectorization

import numpy as np
import pandas as pd

arr = np.array([10, 20, 30])
s = pd.Series([10, 20, 30])

print(arr * 2)
print(s * 2)


[20 40 60]
0    20
1    40
2    60
dtype: int64


Explanation

- Both NumPy arrays and Pandas Series support vectorized multiplication, so every element is multiplied by 2.

- Similarity: Both perform element-wise operations.
- Difference: A NumPy array mainly stores values, while a Pandas Series also has an index.

In [ ]:
# Q2. Boolean Filtering
import pandas as pd

df = pd.DataFrame({
    'Student': ['A', 'B', 'C', 'D'],
    'Marks': [45, 80, 65, 90]
})

result = df[df['Marks'] >= 65]

print(result[['Student', 'Marks']])

  Student  Marks
1       B     80
2       C     65
3       D     90


Answer
- Rows displayed: B, C, D
- Number of rows: 3
- Number of columns: 2

Explanation

- df['Marks'] >= 65 creates a Boolean condition and keeps only rows where the condition is True.

In [4]:
# Q3.  Descriptive statistics
import pandas as pd

df = pd.DataFrame({
    'Marks': [10, 20, 30, 40, 50]
})

print(df['Marks'].mean())
print(df['Marks'].max())
print(df['Marks'].median())


30.0
50
30.0


Explanation
- Mean = 30.0
- Maximum = 50
- Median = 30.0

- The mean is the arithmetic average, while the median is the middle value after sorting. The median is generally less affected by extreme values.

In [5]:
# Q4. Group-wise Analysis
import pandas as pd

df = pd.DataFrame({
    'Department': ['IT', 'HR', 'IT', 'HR'],
    'Salary': [40000, 30000, 60000, 50000]
})

print(df.groupby('Department')['Salary'].mean())


Department
HR    40000.0
IT    50000.0
Name: Salary, dtype: float64


Explanation

groupby('Department') separates the rows by department and mean() calculates the average salary for each group.

In [7]:
# Q5.   Pandas Correlation - Positive
import pandas as pd

df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

print(df['Hours'].corr(df['Marks']))


1.0


Explanation

The correlation coefficient is +1.0, indicating a perfect positive linear relationship. As study hours increase, marks increase proportionally.

In [8]:
# Q6.  Pandas Correlation - Negative
import pandas as pd

df = pd.DataFrame({
    'Price': [10, 20, 30, 40],
    'Demand': [100, 80, 60, 40]
})

print(df['Price'].corr(df['Demand']))


-1.0


Explanation

The correlation is -1.0, indicating a perfect negative linear relationship. As price increases, demand decreases.

### Section B – Code Correction

In [ ]:
# Q1. JSON and CSV
df = pd.read_csv("students.csv", header=None)

#### the correct code is 


In [ ]:
import pandas as pd

df = pd.read_csv("students.csv")
print(df)

In [9]:
# Q2. Data Analysis
# The objective is to display the five highest salaries from a DataFrame. Correct the code
import pandas as pd

df = pd.DataFrame({
    'Employee': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Salary': [30000, 50000, 25000, 60000, 45000, 70000]
})

print(df.sort_values('Salary', ascending=False).head(5))

  Employee  Salary
5        F   70000
3        D   60000
1        B   50000
4        E   45000
0        A   30000


Explanation

ascending=False sorts salaries from highest to lowest, and head(5) selects the first five rows.

In [ ]:
# Q3. Cleaning Data          
#A student wants to replace missing marks with the column's mean but writes code that does not update the DataFrame. Correct the code
import pandas as pd

df = pd.DataFrame({'Marks': [70, None, 90]})

df['Marks'] = df['Marks'].fillna(df['Marks'].mean())

print(df)

   Marks
0   70.0
1   80.0
2   90.0


Explanation

The mean of 70 and 90 is 80, so the missing value is replaced with 80.

In [12]:
# Q4. Correlation
# The objective is to calculate the correlation between Hours and Marks. Correct the code.
import pandas as pd

df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

print(df['Hours'].corr(df['Marks']))

1.0


Explanation

Select the two Series and use Series.corr() to calculate their correlation.

### Section C – Edge Cases


In [13]:
# Q1. NumPy Broadcasting
#Two NumPy arrays have shapes (3, 1) and (1, 3). Predict the shape of their element-wise sum and explain how broadcasting works.
import numpy as np

a = np.array([[10], [20], [30]])

b = np.array([[1, 2, 3]])

result = a + b

print(result)
print(result.shape)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
(3, 3)


**1. Predict the output:**

The output is:

[[11 12 13]
 [21 22 23]
 [31 32 33]]

The shape of the result is (3, 3).

**2. Shapes before addition:**

- Array `a` has shape (3, 1).
- Array `b` has shape (1, 3).

**3. How broadcasting works:**

NumPy broadcasts the dimensions of size 1 so that the two arrays become compatible for element-wise addition. Therefore, the arrays produce a final shape of (3, 3).

**4. If b is replaced with np.array([1, 2]):**

The shapes become (3, 1) and (2,). These shapes are broadcast-compatible, so the result will be:

[[11 12]
 [21 32]
 [31 32]]

In [17]:
# Q2. CSV Parsing, Missing Values and Dates
# A CSV file contains commas inside quoted text fields, missing values, and dates in different formats.
import pandas as pd

df = pd.read_csv("students.csv")

print(df)
print("\n",df.dtypes)

    ID     Name        Date  Marks
0  101  Asha, R  2026-09-01   80.0
1  102     Ravi  01/09/2026    NaN
2  103     Neha  2026-09-03    NaN

 ID         int64
Name         str
Date         str
Marks    float64
dtype: object


### Answers

**1. How is the quoted comma handled?**

The comma inside `"Asha, R"` is treated as part of the Name field because the value is enclosed in double quotes. It does not create an additional column.

**2. Potential issues with Date and Marks columns:**

The Date column contains dates in different formats, such as `2026-09-01` and `01/09/2026`. Therefore, the dates should be converted into a consistent date-time format.

The Marks column contains a missing value and `NA`. These values need to be investigated and handled appropriately before analysis.

**3. Corrected code:**

In [21]:
import pandas as pd

df = pd.read_csv("students.csv")
df["Marks"] = pd.to_numeric(df["Marks"], errors="coerce")
df["Date"] = pd.to_datetime(
    df["Date"],
    format="mixed",
    errors="coerce"
)
print(df)
print("\n",df.dtypes)

    ID     Name       Date  Marks
0  101  Asha, R 2026-09-01   80.0
1  102     Ravi 2026-01-09    NaN
2  103     Neha 2026-09-03    NaN

 ID                int64
Name                str
Date     datetime64[us]
Marks           float64
dtype: object


4. Why should NA be investigated?

The value NA should be investigated because it may represent a missing value, but it could also have a different meaning depending on the dataset. We should understand its meaning before treating it as missing data.

In [ ]:
# Q3. Extreme Salary Value
# A salary column contains the values 25000, 30000, 35000, and 10000000. Explain how the extreme value affects the mean compared with the median.
import pandas as pd

df = pd.DataFrame({
    "Employee": ["A", "B", "C", "D"],
    "Salary": [25000, 30000, 35000, 10000000]
})

print("Mean:", df["Salary"].mean())
print("Median:", df["Salary"].median())

Mean: 2522500.0
Median: 32500.0


### Answers

**1. Predict the mean and median salary.**

Mean = 2,522,500.0

Median = 32,500.0


**2. Identify the effect of the extreme salary on the mean.**

The salary of 10,000,000 is an extreme value. It greatly increases the mean because the mean uses every value in the calculation. The median is much less affected by the extreme value.


**3. Which statistic may better represent a typical employee's salary?**

The median may better represent a typical employee's salary because it is less affected by the extreme salary of 10,000,000. The median salary is 32,500, which is closer to the salaries of employees A, B, and C.


**4. Identify the employee record with the highest salary.**

The following code identifies the employee with the highest salary:

In [23]:
highest_salary = df.loc[df["Salary"].idxmax()]

print(highest_salary)

Employee           D
Salary      10000000
Name: 3, dtype: object


### Section D – Scenario-Based Problems

In [15]:
import pandas as pd
# 1. Load the dataset
df = pd.read_csv("student_assessment_dirty.csv")

# Inspect the dataset
print(df.head())
df.info()
print(df.isnull().sum())

# 2. Standardize Department names
df["Department"] = (
    df["Department"]
    .str.strip()
    .str.upper()
    .replace({
        "I.T.": "IT",
        "FINANCE": "FINANCE"
    })
)

# 3. Remove exact duplicate records
before_duplicates = len(df)
df = df.drop_duplicates()
duplicates_removed = before_duplicates - len(df)

# 4. Preserve original marks for investigation
df["Original_Marks"] = df["Marks"]

# Convert Marks to string first
marks_text = df["Marks"].astype("string").str.strip()

# Identify Absent separately
df["Status"] = marks_text.mask(
    marks_text.isna() | marks_text.isin(["NA", ""]),
    "Missing"
)
df.loc[marks_text.str.lower() == "absent", "Status"] = "Absent"

# Remove "marks" text from values such as "88 marks"
clean_marks = (
    marks_text
    .str.replace("marks", "", case=False, regex=False)
    .str.strip()
)

# Convert to numeric
df["Marks"] = pd.to_numeric(clean_marks, errors="coerce")

  Student_ID Student_Name Department Assessment   Marks
0       S101         Asha         IT     Python      85
1       S102         Ravi         it     Python      78
2       S103         Neha       I.T.     Python      92
3       S104        Karan         HR     Python     NaN
4       S105        Meera         HR     Python  Absent
<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student_ID    15 non-null     str  
 1   Student_Name  15 non-null     str  
 2   Department    15 non-null     str  
 3   Assessment    15 non-null     str  
 4   Marks         12 non-null     str  
dtypes: str(5)
memory usage: 732.0 bytes
Student_ID      0
Student_Name    0
Department      0
Assessment      0
Marks           3
dtype: int64


In [13]:
# 5. Identify invalid marks
invalid_mask = (df["Marks"] < 0) | (df["Marks"] > 100)

invalid_records = df[invalid_mask].copy()

print("Invalid marks:")
print(invalid_records)

# Convert invalid marks to missing
df.loc[invalid_mask, "Marks"] = pd.NA
df.loc[invalid_mask, "Status"] = "Invalid"



Invalid marks:
Empty DataFrame
Columns: [Student_ID, Student_Name, Department, Assessment, Marks, Original_Marks, Status]
Index: []


In [14]:
# Display cleaned DataFrame
print("\nCleaned DataFrame:")
print(df)


Cleaned DataFrame:
   Student_ID Student_Name Department Assessment  Marks Original_Marks  \
0        S101         Asha         IT     Python     85             85   
1        S102         Ravi         IT     Python     78             78   
2        S103         Neha         IT     Python     92             92   
3        S104        Karan         HR     Python   <NA>            NaN   
4        S105        Meera         HR     Python   <NA>         Absent   
5        S106        Arjun    FINANCE     Python      0              0   
6        S107        Priya    FINANCE     Python     67             67   
7        S108        Rahul         IT     Python     75             75   
9        S109        Sneha         IT     Python   <NA>            NaN   
10       S110        Varun         HR     Python     88       88 marks   
11       S111         Diya    FINANCE     Python     91             91   
12       S112         Aman         IT     Python   <NA>            NaN   
13       S113     

In [ ]:
print("\nDuplicate records removed:", duplicates_removed)
print("Original missing/absent marks:", 
      df["Original_Marks"].isin(["", "NA", "Absent"]).sum())
print("Invalid marks identified:", len(invalid_records))
print("Missing numeric marks remaining:", df["Marks"].isna().sum())


Duplicate records removed: 1
Original missing/absent marks: 1
Invalid marks identified: 0
Missing numeric marks remaining: 5


### Explanation

The dataset was cleaned by standardizing department names, removing exact duplicate records, converting the Marks column to numeric values, handling missing and absent marks, and identifying marks outside the valid range of 0–100.

The value "88 marks" was converted to 88. "Absent" was kept as a separate status, while blank and "NA" values were treated as missing after investigation.

The mark 105 was identified as invalid because valid marks must be between 0 and 100.

Missing values should not be deleted without investigation because they may have different meanings, such as a student being absent or marks not yet being entered. Deleting them blindly can result in loss of information and potentially misleading analysis.